config/routes.rb
Rails.application.routes.draw do
  devise_for :users

   root 'todos#index'

    resources :todos do
       member do
        post 'finish'
       end
     end

end

app/models/todo.rb
class Todo < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
    before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
	def index
		if params[:finishOrNot].blank?
			@todos=Todo.all
		end
		if params[:finishOrNot].present?
			@todos=Todo.where(:finishOrNot => true)
		end
		if params[:finishNot].present?
			@todos=Todo.where(:finishOrNot => false)		
		end
	end

	def new
		@todo = Todo.new
	end

	def edit
		@todo = Todo.find(params[:id])
	end

	def create
		@todo=Todo.new(todo_params)
		if @todo.save
			redirect_to root_path
		else
			render :new
		end
	end

	def update
		@todo = Todo.find(params[:id])
		if @todo.update(todo_params)
			redirect_to root_path
		else
			render :edit
		end
	end

	def destroy
		@todo=Todo.find(params[:id])
		@todo.destroy
		redirect_to root_path
	end

	def finish
		@todo=Todo.find(params[:id])
		if @todo.finishOrNot == false
			@todo.update_attributes(finishOrNot: true)
			redirect_to root_path
		else
			@todo.update_attributes(finishOrNot: false)
			redirect_to root_path
		end
	end

	private
	def todo_params
		params.require(:todo).permit(:content, :finishOrNot)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todo_helper.rb
module TodoHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todolist</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<% if user_signed_in? %>
	<%=current_user.name%>你好
	<%= link_to "登出", destroy_user_session_path,method:'delete' %>
	<% else %>
	<%= link_to "註冊", new_user_registration_path %>
	<%= link_to "登入", new_user_session_path %>
	<% end %>

<%= yield %>

</body>
</html>

app/views/todos/edit.html.erb
<h2>Edit your todo</h2>
<%= form_for @todo do |f|%>
	<div>
		new todo thing
		<%= f.text_field :content %>
	</div>
	<div>
		finished or not?
		<%= f.check_box :finishOrNot %> Yes!
	</div>

	<%=f.submit %>
<% end %>

app/views/todos/index.html.erb
<h2>Todo list</h2>
<div>
	<%= link_to "Your new todo", new_todo_path %>
</div>
<br>
Search for
<%= form_tag todos_path, method:"get" do %>
	<%= hidden_field_tag :finishOrNot, true %>
	<%=submit_tag "What you have finished" %>
<% end %>
<%= form_tag todos_path, method:"get" do %>
	<%= hidden_field_tag :finishNot, false %>
	<%=submit_tag "What you haven't finished" %>
<% end %>

<br>
<% @todos.each do |todo|%>

<%=todo.content %>
	<% if todo.finishOrNot ==false %>
		(Not yet finished)
	<% else %>
		(Finished)
<% end %>
<% if todo.finishOrNot ==false %>
	<%=button_to "Turn to Finished", finish_todo_path(todo),method: :post %>
<% else %>
	<%=button_to "Turn to not finished", finish_todo_path(todo),method: :post %>
<% end %>
<%= link_to "Delete todo", todo_path(todo),method:"delete" %>
<%= link_to "Edit your todo", edit_todo_path(todo) %>
<br>
<% end %>

app/views/todos/new.html.erb
<h2>Your new todo</h2>
<%= form_for @todo do |f|%>
	<div>
		new todo thing
		<%= f.text_field :content %>
	</div>
	<div>
		finished or not?
		<%= f.check_box :finishOrNot %> Yes!
	</div>

	<%=f.submit %>
<% end %>